# In this hands-on project, we will understand the fundamentals of data analysis in Python and we will leverage the power of two important python libraries known as Numpy and pandas.

# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np #loading library

# Let's define a one-dimensional array 

list_1 = [50,60,80,100,200,300,500,600]

# Let's create a numpy array from the list "list_1"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [2]:
type(my_numpy_array)

numpy.ndarray

In [3]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2,5,8], [7,3,6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1:

Write a code that creates the following 2x4 numpy array
[[3 7 9 3] 
[4 3 2 2]]

In [4]:
challenge1 = np.array([ [3,7,9,3],[4,3,2,2]   ])
challenge1

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [5]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.54821326, 0.62276521, 0.68735654, 0.81260553, 0.16430445,
       0.96162029, 0.13389927, 0.42440742, 0.01842498, 0.84736402,
       0.92677942, 0.3277683 , 0.89452978, 0.59300175, 0.47934376,
       0.25811974, 0.65218906, 0.74896346, 0.00618012, 0.3988214 ])

In [6]:
# you can create a matrix of random number as well which is 3 by 3
x = np.random.rand(3,3)
x

array([[0.0257535 , 0.0742983 , 0.36859327],
       [0.07554952, 0.81702438, 0.12664775],
       [0.62448085, 0.94912774, 0.26034924]])

In [7]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x


24

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50,5)
x

array([27, 39, 13, 48, 26])

In [9]:
type(x)

numpy.ndarray

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
x = np.zeros((4,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

MINI CHALLENGE #2:

Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"
int


In [54]:
x = int(input("Please enter a positive integer value: "))      
x = np.random.randint(0,x,10)
x

Please enter a positive integer value:  22


array([18,  9,  7, 13, 17, 16,  9,  1, 20,  9])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [14]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [18]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:

Given the X and Y values below, obtain the distance between them
X = [5, 7, 20]
Y = [9, 15, 4]

In [20]:
x = np.array([5,7,20])
y = np.array([9,15,4])
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [21]:
my_numpy_array = np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [22]:
# Access specific index from the numpy array
my_numpy_array[-1] #last element

50

In [23]:
# Starting from the first index 0 up until and NOT including the last element
# Access specific index from the numpy array
my_numpy_array[0:3]

array([3, 5, 6])

In [24]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [25]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[7, 6, 5, 9],
       [9, 3, 1, 2],
       [7, 4, 2, 4],
       [4, 2, 1, 6]])

In [26]:
# Get a row from a mtrix
matrix[-1]# Get a row from a mtrix
matrix[-1]

array([4, 2, 1, 6])

In [27]:
# Get one element
matrix[0][2]

5

MINI CHALLENGE #4:

In the following matrix, replace the last row with 0
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]

In [28]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [29]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[2, 2, 5, 4, 5],
       [5, 6, 7, 9, 8],
       [2, 9, 6, 1, 5],
       [6, 2, 6, 2, 7],
       [4, 9, 3, 3, 7]])

In [30]:
new_matrix= matrix[matrix > 5]
new_matrix

array([6, 7, 9, 8, 9, 6, 6, 6, 7, 9, 7])

In [31]:
# Obtain odd elements only
new_matrix = matrix[matrix % 2 == 1]
new_matrix

array([5, 5, 5, 7, 9, 9, 1, 5, 7, 9, 3, 3, 7])

MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]

In [32]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X[X < 0] = 0
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS¶

In [33]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [34]:
import pandas as pd

In [35]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444], 'Bank Client Name':['Chanel', 'Steve','Mitch','Ryan'],
                              "Net worth [$]":[3500,29000,10000,2000],'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [36]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [37]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [38]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

MINI CHALLENGE #6:

A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
Calculate the total value of the porfolio including all stocks

In [39]:
portfolio_df = pd.DataFrame({'Stock Ticker Symbol':['AAPL','AMZN','TSLA'],'Number of Shares':[3,4,9],'Price Per Share [$]':[3500,200,40]})
portfolio_df

Stock Ticker Symbol  Number of Shares  Price Per Share [$]
0                AAPL                 3                 3500
1                AMZN                 4                  200
2                TSLA                 9                   40

In [40]:
#Calculate the total value of the porfolio including all stocks
stocks_dollar_value = portfolio_df['Price Per Share [$]'] * portfolio_df['Number of Shares']
stocks_dollar_value.sum()


11660

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [41]:
#read tabular data using read_html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [42]:
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [43]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:

Write a code that uses Pandas to read tabular US retirement data
You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [44]:
US_Retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
US_Retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [45]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5]
df_loyal

Bank Client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [46]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [47]:
df_high_Networth = bank_client_df[bank_client_df['Net worth [$]'] >= 5000]
df_high_Networth

Bank Client Name  Net worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [48]:
df_high_Networth['Net worth [$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [49]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [50]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:

Define a function that triples the stock prices and adds $200
Apply the function to the DataFrame


In [51]:
def networth_update(balance):
    return balance * 3 +200

In [52]:
bank_client_df['Net worth [$]'].apply(networth_update)

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [53]:
#Calculate the updated total networth of all clients combined
result = bank_client_df['Net worth [$]'].apply(networth_update)
result.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [55]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [56]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by ='Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [57]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [61]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by ='Years with bank', inplace = True)

In [62]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [67]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
df1 = pd.DataFrame({'A':['A0','A1','A2', 'A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']
                   },
                  index = [0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [69]:
df2 = pd.DataFrame({'A':['A4','A5','A6', 'A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [70]:
df3 = pd.DataFrame({'A':['A8','A9','A10', 'A11'],
                   'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],
                   'D':['D8','D9','D10','D11']},
                  index = [8,9,10,11])

In [71]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
Merge client names and their newly added salary information using the 'Bank Client ID'
Let's assume that you became a new client to the bank
Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
Add this new dataframe to the original dataframe 'bank_df_a

In [115]:
Bank_df_1 = pd.DataFrame({'Bank Client ID':[1,2,3,4,5],'First name':['Ryan', 'Jack','Tom', 'Mia','Jeni'],'Last name':
                          ['Andrew','Ng', 'Cruise','Henry','Nick']},
                         index=[0,1,2,3,4]
                         )
Bank_df_2 = pd.DataFrame({'Bank Client ID':[6,7,8,9,10],'First name':['Ron', 'Matt,','Tony', 'Pia','JJ'],'Last name':
                          ['Ang','Sam', 'Cruise','Bhatt','Nick']},
                         index=[5,6,7,8,9]
                         )
bank_df_all = pd.concat([Bank_df_1,Bank_df_2])
raw_data = {'Bank Client ID': [1,2,3,4,5,6,7,8,9,10],'Annual Salary [$/year]':[50000,50000,70000,100000,35000,60000,200000,45000,70000,40000]}
bank_df_salary = pd.DataFrame(raw_data,columns=['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary
bank_df_all = pd.merge(bank_df_all,bank_df_salary, on='Bank Client ID')
bank_df_all

Bank Client ID First name Last name  Annual Salary [$/year]
0               1       Ryan    Andrew                   50000
1               2       Jack        Ng                   50000
2               3        Tom    Cruise                   70000
3               4        Mia     Henry                  100000
4               5       Jeni      Nick                   35000
5               6        Ron       Ang                   60000
6               7      Matt,       Sam                  200000
7               8       Tony    Cruise                   45000
8               9        Pia     Bhatt                   70000
9              10         JJ      Nick                   40000

In [95]:
new_client = {'Bank Client ID':['11'],'First name':['Kya'],'Last name':['Liz'],'Annual Salary [$/year]':[80000]}

In [96]:
new_client_df = pd.DataFrame(new_client,columns=['Bank Client ID','First name','Last name','Annual Salary [$/year]'])

In [114]:
new_client_df

Bank Client ID First name Last name  Annual Salary [$/year]
0             11        Kya       Liz                   80000

In [106]:
#bank_df_all = pd.concat([bank_df_all,new_client_df])


In [116]:
bank_df_all

Bank Client ID First name Last name  Annual Salary [$/year]
0               1       Ryan    Andrew                   50000
1               2       Jack        Ng                   50000
2               3        Tom    Cruise                   70000
3               4        Mia     Henry                  100000
4               5       Jeni      Nick                   35000
5               6        Ron       Ang                   60000
6               7      Matt,       Sam                  200000
7               8       Tony    Cruise                   45000
8               9        Pia     Bhatt                   70000
9              10         JJ      Nick                   40000

In [117]:
new_client_df

Bank Client ID First name Last name  Annual Salary [$/year]
0             11        Kya       Liz                   80000

In [118]:
new_df = pd.concat([bank_df_all,new_client_df],axis =0)

In [119]:
new_df

Bank Client ID First name Last name  Annual Salary [$/year]
0              1       Ryan    Andrew                   50000
1              2       Jack        Ng                   50000
2              3        Tom    Cruise                   70000
3              4        Mia     Henry                  100000
4              5       Jeni      Nick                   35000
5              6        Ron       Ang                   60000
6              7      Matt,       Sam                  200000
7              8       Tony    Cruise                   45000
8              9        Pia     Bhatt                   70000
9             10         JJ      Nick                   40000
0             11        Kya       Liz                   80000

In [123]:
new_df.columns

Index(['Bank Client ID', 'First name', 'Last name', 'Annual Salary [$/year]'], dtype='object')